theme: liddlelab-theme
name: "Liddle Laboratory"
title: "Liddle Laboratory"
baseurl: "https://stm32.liddlelaboratory.com//"

exclude:
  - Chapter1
  - Chapter0
  - Template
  - cpplint.cfg
  - init.ps1
  - init.sh
  - LICENSE
  - shared
  - tools
  - README.md
  - Chapter2
