#!/bin/bash

# Find all markdown files in Chapter* folders
markdown_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '^Chapter[^/]+/.*\.md$')

# I don't want to take a npm dependency for a formatter... We'll see what I do here.
# Check if there are any markdown files to format
# if [ -n "$markdown_files" ]; then
    # echo "Formatting markdown files..."
    
    # # Format each markdown file and re-add it to the staging area
    # for file in $markdown_files; do
    #     # Format the file (replace `prettier` with your formatter if needed)
    #     prettier --write "$file"
        
    #     # Re-add the formatted file to the staging area
    #     git add "$file"
    # done
# fi

cpplint --recursive .

echo "updating headers in files"
FILES=$(python3 tools/scripts/update_headers.py)

for FILE in $FILES; do
    # Remove trailing '?' if it exists
    CLEAN_FILE=$(echo $FILE | sed 's/\?$//')

    # Check if the file is empty
    if [ -s "$CLEAN_FILE" ]; then
        git add "$CLEAN_FILE"
    fi
done
